---
title: "git_01"
author: "Arlene Faye Salvador"
date: "September 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Little Birds are dining  
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters -

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I have wished a bird would fly away,  
And not sing by my house all day;  

Have clapped my hands at him from the door  
When it seemed as if I could bear no more.  

The fault must partly have been in me.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright — 
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The rain drums down like red ants,  
each bouncing off my window.  
The ants are in great pain  
and they cry out as they hit  
as if their little legs were only  
stitched on and their heads pasted.  
And oh they bring to mind the grave,  
so humble, so willing to be beat upon  
with its awful lettering and  
the body lying underneath  
without an umbrella.  
Depression is boring, I think  
and I would do better to make  
some soup and light up the cave.